### ISSUE TITLE
Behavior Settings

### ISSUE THREAD

**Issue by tommoor** [pushbit-co/platform#34]
Most of the behaviors seem to need some sort of settings attaching to them which will then be provided to the docker container. 

This means another bit of config that we should read from the repo and import when we sync behaviors... we need to come up with a decent format for describing settings so that we can dynamically construct forms.

@awsmsrc let me know if you think I'm wildly off-base here.

**Comment by tommoor** [comment]
I added `behavior.settings` on the `new-design` branch, it takes the form of:

```yaml
settings:
  settingName:
    label: This label will appear against the input in the pushbit UI
    type: string / integer / etc
    options: 
      - Optional
      - Array
      - Of 
      - Options
```

Next up is to read this data from the db and add the settings field to the UI.
Then save those values against the active behavior.
